### ISSUE TITLE
The Problem When Compile Ops During Training

### ISSUE THREAD

**Issue by otakuxiang** [Jittor/shapenet-reconstruction-jittor#1]
I just follow the Readme file and running 
python train.py -eid rcon
After loading dataset it comes a Error:
[e 1211 15:40:51.203588 32:C8 parallel_compiler.cc:261] [Error] source file location: /home/chx/.cache/jittor/default/g++/jit/_opkey0:broadcast_to_Tx:float32__DIM=3__BCAST=4__JIT:1__JIT_cuda:1__index_t:int32___opkey1...hash:3393288417c3934_op.cc

The whole log during running :
```
[i 1211 15:40:06.151589 04 __init__.py:257] Found g++(7.1.0) at g++
[i 1211 15:40:06.169415 72 compiler.py:839] Jittor(1.2.2.1) src: /home/chx/pyenv/jittor/lib/python3.7/site-packages/jittor
[i 1211 15:40:06.169498 72 compiler.py:840] cache_path: /home/chx/.cache/jittor/default/g++
[i 1211 15:40:06.172431 72 compiler.py:791] Found /usr/local/cuda/bin/nvcc(10.0.130) at /usr/local/cuda-10.0/bin/nvcc
[i 1211 15:40:06.238758 72 __init__.py:249] Found gdb(7.11.1) at /usr/bin/gdb.
[i 1211 15:40:06.245545 72 __init__.py:249] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 1211 15:40:06.281101 72 compiler.py:889] pybind_include: -I/home/chx/pyenv/jittor/include/python3.7m -I/home/chx/pyenv/jittor/lib/python3.7/site-packages/pybind11/include
[i 1211 15:40:06.311328 72 compiler.py:891] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
[i 1211 15:40:06.451266 72 __init__.py:168] Total mem: 47.00GB, using 15 procs for compiling.
[i 1211 15:40:06.662825 72 jit_compiler.cc:20] Load cc_path: g++
[i 1211 15:40:06.662844 72 jit_compiler.cc:23] Load nvcc_path: /usr/local/cuda-10.0/bin/nvcc
[i 1211 15:40:06.663350 72 init.cc:51] Found cuda archs: [61,]
[i 1211 15:40:06.763959 72 __init__.py:249] Found mpicc(1.10.2) at /usr/bin/mpicc.
[i 1211 15:40:06.792622 72 compiler.py:646] handle pyjt_include/home/chx/pyenv/jittor/lib/python3.7/site-packages/jittor/extern/mpi/inc/mpi_warper.h
[i 1211 15:40:06.813325 72 compile_extern.py:266] Downloading nccl...
Data file has been downloaded and verified
[i 1211 15:40:06.871386 72 compile_extern.py:15] found /usr/local/cuda-10.0/include/cublas.h
[i 1211 15:40:06.871482 72 compile_extern.py:15] found /usr/local/cuda-10.0/lib64/libcublas.so
[i 1211 15:40:07.077687 72 compile_extern.py:15] found /usr/local/cuda-10.0/include/cudnn.h
[i 1211 15:40:07.077773 72 compile_extern.py:15] found /usr/local/cuda-10.0/lib64/libcudnn.so
[i 1211 15:40:07.086045 72 compiler.py:646] handle pyjt_include/home/chx/pyenv/jittor/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h
[i 1211 15:40:07.866171 72 compile_extern.py:15] found /usr/local/cuda-10.0/include/curand.h
[i 1211 15:40:07.866263 72 compile_extern.py:15] found /usr/local/cuda-10.0/lib64/libcurand.so
[i 1211 15:40:07.895576 72 cuda_flags.cc:25] CUDA enabled.
[i 1211 15:40:08.108591 72 cuda_flags.cc:25] CUDA enabled.
Loading dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:32<00:00,  2.49s/it]
[e 1211 15:40:51.203588 32:C8 parallel_compiler.cc:261] [Error] source file location: /home/chx/.cache/jittor/default/g++/jit/_opkey0:broadcast_to_Tx:float32__DIM=3__BCAST=4__JIT:1__JIT_cuda:1__index_t:int32___opkey1...hash:3393288417c3934_op.cc
[e 1211 15:40:51.203597 32:C8 parallel_compiler.cc:264] Compile fused operator(24/65) failed: [Op(0x55e55dc46f00:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc46fb0),Op(0x55e55dc55b80:0:1:1:i0:o1:s0,array->0x55e55dc55c20),Op(0x55e55dc47ce0:1:1:2:i1:o1:s0,broadcast_to->0x55e55dc47d90),Op(0x55e55dc47a40:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc47af0),Op(0x55e55dc47f20:0:1:1:i0:o1:s0,array->0x55e55dc47fc0),Op(0x55e55dc556e0:1:1:2:i1:o1:s0,broadcast_to->0x55e55dc55790),Op(0x55e55dc46c60:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc46d10),Op(0x55e55dc463a0:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc46450),Op(0x55e55dc46100:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc461b0),Op(0x55e55dc53db0:0:1:1:i0:o1:s0,array->0x55e55dc53e50),Op(0x55e55dc57820:1:1:2:i1:o1:s0,broadcast_to->0x55e55dc578d0),Op(0x55e55dc5b770:1:1:2:i1:o1:s0,broadcast_to->0x55e55dc5b820),Op(0x55e55dc56040:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc560f0),Op(0x55e55dc477a0:1:1:2:i2:o1:s0,binary.multiply->0x55e55dc47830),Op(0x55e55dc48380:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc48430),Op(0x55e55dc469e0:0:1:1:i2:o1:s0,binary.multiply->0x55e55dc46a70),Op(0x55e55dc45ed0:0:1:1:i2:o1:s0,binary.multiply->0x55e55dc45f60),Op(0x55e55dc54230:0:1:1:i1:o1:s0,broadcast_to->0x55e55dc542e0),Op(0x55e55d9e15b0:2:0:1:i2:o1:s0,binary.multiply->0x55e55d9e1640),Op(0x55e55dc480c0:1:1:2:i2:o1:s0,binary.multiply->0x55e55dc48150),Op(0x55e55dc47140:0:1:1:i2:o1:s0,binary.add->0x55e55dc471d0),Op(0x55e55d7a3220:2:0:1:i2:o1:s0,binary.multiply->0x55e55d7a32b0),Op(0x55e55d7a21c0:2:0:1:i2:o1:s0,binary.multiply->0x55e55d7a2250),Op(0x55e55dc53fb0:0:1:1:i2:o1:s0,binary.subtract->0x55e55dc54040),Op(0x55e55d8bb820:2:0:1:i2:o1:s0,binary.divide->0x55e55d8bb8b0),Op(0x55e55d8bbaa0:1:0:1:i1:o1:s0,unary.negative->0x55e55d8b40e0),Op(0x55e55dc55480:1:1:2:i2:o1:s0,binary.multiply->0x55e55dc55510),Op(0x55e55dc55980:1:1:2:i2:o1:s0,binary.add->0x55e55dc55a10),Op(0x55e55dc55d80:1:1:2:i2:o1:s0,binary.subtract->0x55e55dc55e10),Op(0x55e55dc57580:2:1:2:i2:o1:s0,binary.multiply->0x55e55dc57610),Op(0x55e55d8baab0:2:0:1:i2:o1:s0,binary.multiply->0x55e55d8bab40),Op(0x55e55dc5b570:2:1:2:i2:o1:s0,binary.divide->0x55e55dc5b600),Op(0x55e55d8b4250:2:0:1:i2:o1:s0,binary.multiply->0x55e55d8b42e0),Op(0x55e55d8c7290:1:0:1:i1:o1:s0,reduce.add->0x55e55d8c7320),Op(0x55e55d9e1830:2:0:1:i2:o1:s0,binary.divide->0x55e55d9e0ee0),Op(0x55e55d9e2510:1:0:1:i1:o1:s0,reduce.add->0x55e55d8c2160),] 

Reason: [f 1211 15:40:51.200407 32:C8 const_var_pass.cc:41] Check failed: def  Something wrong... Could you please report this issue?

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    train()
  File "train.py", line 138, in train
    model.save(model_path)
  File "/home/chx/pyenv/jittor/lib/python3.7/site-packages/jittor/__init__.py", line 649, in save
    params_dict[p.name()] = p.data
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.data)).

Types of your inputs are:
 self   = Var,

The function declarations are:
 inline DataView data()

Failed reason:[f 1211 15:40:56.068589 72 parallel_compiler.cc:316] Error happend during compilation, see error above.
```
I use g++ instead of clang++ is that problem? 
My operation system is Ubuntu16.04 and cuda version is 10.0

**Comment by otakuxiang** [comment]
I just update jittor to 1.2.2.2 and solve the problem.
